#!/usr/bin/env python3
"""Verify that every `com.sublearn.*` import resolves to a declaration in the repository.

The sandbox cannot run Gradle, so this catches the most common class of mistake in hand-written
multi-module Kotlin: importing or naming a type/member that was never written. It is a name check,
not a type check; `./gradlew :app:compileDebugKotlin` (in CI) remains the authority.

Usage: python3 tools/check_symbols.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

DECL = re.compile(
    r"^\s*(?:@\w+\s+)*(?:public |internal |private |abstract |open |sealed |data |value |enum |annotation |)*"
    r"(?:fun\s+interface|class|interface|object|fun|val|var|typealias)\s+(?:[\w.<>]+\.)?`?(\w+)`?",
    re.M,
)
# Resource and config classes are generated by the Android plugin, so they never appear in sources.
GENERATED = {"R", "BuildConfig"}
TOP_LEVEL = re.compile(r"^(class|interface|object|enum|annotation|fun|val|var|typealias)\b")
IMPORT = re.compile(r"^import\s+(com\.sublearn\.[\w.]+)(?:\s+as\s+(\w+))?")
PKG = re.compile(r"^package\s+([\w.]+)")


def declarations(root: Path) -> dict[str, set[str]]:
    """package -> declared member names (types and top-level members)."""
    out: dict[str, set[str]] = {}
    for path in root.rglob("*.kt"):
        if "build" in path.parts:
            continue
        text = path.read_text()
        match = PKG.search(text)
        if not match:
            continue
        package = match.group(1)
        bucket = out.setdefault(package, set())
        for line in text.splitlines():
            stripped = line.rstrip()
            if not line[:1].strip():
                continue
            if line.strip() in {"}", "{", ""}:
                continue
            if TOP_LEVEL.match(line) or "class " in line or "interface " in line or "object " in line:
                found = DECL.match(stripped)
                if found:
                    bucket.add(found.group(1))
                # `enum class Foo` / `sealed class Foo`
                name = re.search(r"\b(\w+)\s*(?:\(|:|$)", stripped.split("class ")[-1]) if "class " in stripped else None
                if name:
                    bucket.add(name.group(1))
            # nested types and members: record names so `Outer.member` imports resolve
            found = DECL.match(stripped)
            if found:
                bucket.add(found.group(1))
            # enum entries and companion constants, which are imported as `Type.ENTRY`
            for entry in re.finditer(r"^\s{4}([A-Z][A-Z0-9_]{2,})\s*[,;(]", text, re.M):
                bucket.add(entry.group(1))
            for entry in re.finditer(r"^\s{4}([a-z][\w]*)(?=\s*[,;])", text, re.M):
                bucket.add(entry.group(1))
        out[package] = bucket
    return out


def main(argv: list[str]) -> int:
    root = Path(".")
    decls = declarations(root)
    problems: list[str] = []
    for path in sorted(list(root.glob("*/src/**/*.kt")) + list(root.glob("*/*/src/**/*.kt"))):
        if "/build/" in str(path):
            continue
        for line in path.read_text().splitlines():
            match = IMPORT.match(line)
            if not match:
                continue
            fqn = match.group(1)
            parts = fqn.split(".")
            if parts[-1] in GENERATED:
                continue
            # walk back until a package prefix is known; the rest must be a member of it
            for split in range(len(parts) - 1, 1, -1):
                package = ".".join(parts[:split])
                member = parts[split]
                if package in decls:
                    names = decls[package]
                    if member not in names and not any(n.endswith("." + member) for n in names):
                        problems.append(f"{path}: unresolved import {fqn}")
                    break
            else:
                problems.append(f"{path}: unknown package in import {fqn}")
    for problem in problems:
        print(problem)
    print(f"checked imports, {len(problems)} unresolved")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
