#!/usr/bin/env python3
"""Verify that every `com.sublearn.*` import resolves to a declaration in the repository.

The sandbox cannot run Gradle, so this catches the most common class of mistake in hand-written
multi-module Kotlin: importing or naming a type/member that was never written. It is a name check,
not a type check; `./gradlew :app:compileDebugKotlin` (in CI) remains the authority.

Usage: python3 tools/check_symbols.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

DECL = re.compile(
    r"^\s*(?:@\w+\s+)*(?:public |internal |private |abstract |open |sealed |data |value |enum |annotation |)*"
    r"(?:fun\s+interface|class|interface|object|fun|val|var|typealias)\s+(?:[\w.<>]+\.)?`?(\w+)`?",
    re.M,
)
# Resource and config classes are generated by the Android plugin, so they never appear in sources.
GENERATED = {"R", "BuildConfig"}
TOP_LEVEL = re.compile(r"^(class|interface|object|enum|annotation|fun|val|var|typealias)\b")
IMPORT = re.compile(r"^import\s+(com\.sublearn\.[\w.]+)(?:\s+as\s+(\w+))?")
PKG = re.compile(r"^package\s+([\w.]+)")


def declarations(root: Path) -> dict[str, set[str]]:
    """package -> declared member names (types and top-level members)."""
    out: dict[str, set[str]] = {}
    for path in root.rglob("*.kt"):
        if "build" in path.parts:
            continue
        text = path.read_text()
        match = PKG.search(text)
        if not match:
            continue
        package = match.group(1)
        bucket = out.setdefault(package, set())
        for line in text.splitlines():
            stripped = line.rstrip()
            if not line[:1].strip():
                continue
            if line.strip() in {"}", "{", ""}:
                continue
            if TOP_LEVEL.match(line) or "class " in line or "interface " in line or "object " in line:
                found = DECL.match(stripped)
                if found:
                    bucket.add(found.group(1))
                # `enum class Foo` / `sealed class Foo`
                name = re.search(r"\b(\w+)\s*(?:\(|:|$)", stripped.split("class ")[-1]) if "class " in stripped else None
                if name:
                    bucket.add(name.group(1))
            # nested types and members: record names so `Outer.member` imports resolve
            found = DECL.match(stripped)
            if found:
                bucket.add(found.group(1))
            # enum entries and companion constants, which are imported as `Type.ENTRY`
            for entry in re.finditer(r"^\s{4}([A-Z][A-Z0-9_]{2,})\s*[,;(]", text, re.M):
                bucket.add(entry.group(1))
            for entry in re.finditer(r"^\s{4}([a-z][\w]*)(?=\s*[,;])", text, re.M):
                bucket.add(entry.group(1))
        out[package] = bucket
    return out


TOP_TYPE = re.compile(
    r"^(?:@[\w.]+\s+)*(?:(?:public|internal|private|abstract|open|sealed|data|value|enum|annotation)\s+)*"
    r"(?:class|interface|object|typealias)\s+`?(\w+)`?",
    re.M,
)
USED_TYPE = re.compile(r"(?<![\w.$])([A-Z][A-Za-z0-9_]*)\b")
ANY_IMPORT = re.compile(r"^import\s+([\w.]+)(?:\s+as\s+(\w+))?", re.M)


def strip_noise(text: str) -> str:
    """Source with comments and string literals removed, so prose cannot look like code."""
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.S)
    text = re.sub(r"//[^\n]*", " ", text)
    text = re.sub(r"\"\"\".*?\"\"\"", '""', text, flags=re.S)
    text = re.sub(r'"(?:\\.|[^"\\\n])*"', '""', text)
    text = re.sub(r"'(?:\\.|[^'\\])*'", "' '", text)
    return text


def missing_imports(root: Path) -> list[str]:
    """Names a file uses that only exist in another package, without an import for them.

    The mirror image of the import check: `Unresolved reference` for a type that exists elsewhere in
    the repo is the cheapest possible mistake to make and the most expensive to discover through CI.
    """
    declared: dict[str, set[str]] = {}
    files: list[tuple[Path, str, str, str]] = []
    for path in sorted(root.rglob("*.kt")):
        if "build" in path.parts or ".git" in path.parts:
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        package = PKG.search(text)
        if not package:
            continue
        names = set(TOP_TYPE.findall(text))
        declared.setdefault(package.group(1), set()).update(names)
        files.append((path, package.group(1), text))
    problems: list[str] = []
    for path, package, text in files:
        body = strip_noise(text)
        imports = set()
        star_packages = set()
        for match in ANY_IMPORT.finditer(body):
            target, alias = match.group(1), match.group(2)
            if target.endswith("*"):
                star_packages.add(target[:-2])
            else:
                imports.add(alias or target.rsplit(".", 1)[-1])
        own = set(TOP_TYPE.findall(body))
        local = declared.get(package, set())
        for name in sorted(set(USED_TYPE.findall(body))):
            if name in GENERATED or name in imports or name in own or name in local:
                continue
            if star_packages:
                continue  # a wildcard could legitimately provide it
            # Package-level types elsewhere in the repo are only reachable through an import.
            providers = {other for other, names in declared.items() if name in names}
            if not providers:
                continue
            problems.append(f"{path}: uses {name} (declared in {', '.join(sorted(providers))}) with no import")
    return problems


def main(argv: list[str]) -> int:
    root = Path(".")
    decls = declarations(root)
    problems: list[str] = missing_imports(root)
    for path in sorted(list(root.glob("*/src/**/*.kt")) + list(root.glob("*/*/src/**/*.kt"))):
        if "/build/" in str(path):
            continue
        for line in path.read_text().splitlines():
            match = IMPORT.match(line)
            if not match:
                continue
            fqn = match.group(1)
            parts = fqn.split(".")
            if parts[-1] in GENERATED:
                continue
            # walk back until a package prefix is known; the rest must be a member of it
            for split in range(len(parts) - 1, 1, -1):
                package = ".".join(parts[:split])
                member = parts[split]
                if package in decls:
                    names = decls[package]
                    if member not in names and not any(n.endswith("." + member) for n in names):
                        problems.append(f"{path}: unresolved import {fqn}")
                    break
            else:
                problems.append(f"{path}: unknown package in import {fqn}")
    for problem in problems:
        print(problem)
    print(f"checked imports, {len(problems)} unresolved")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
